import { useMigrations as useDrizzleMigrations } from 'drizzle-orm/expo-sqlite/migrator';

import { db } from './client';
// Generated by `npm run db:generate` (driver: 'expo'). Do not edit by hand.
import migrations from './migrations/migrations';

/**
 * Runs any pending Drizzle migrations on app start.
 * Returns { success, error } — gate the UI on `success` before reading the database.
 */
export function useDatabaseMigrations() {
  return useDrizzleMigrations(db, migrations);
}
